import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("screen");

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "black",
    flex: 1,
  },
  background: { width: "100%", height: "100%", position: "absolute" },
  header: {
    flexDirection: "row",
    paddingHorizontal: 40,
    marginBottom: 30,
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 50,
  },
  logo: {
    height: 40,
    width: 25,
    borderRadius: 100,
    backgroundColor: "#580bdc",
  },
  profile: {
    height: 60,
    width: 60,
    borderRadius: 100,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  middle: { padding: 30 },
  welcome: { fontSize: 36, color: "white", fontWeight: "300" },
  username: { fontSize: 36, color: "white", fontWeight: "bold" },
  search: {
    height: 60,
    backgroundColor: "#0B0B0B",
    borderRadius: 100,
    borderColor: "#202020",
    borderWidth: 0.5,
    marginTop: 30,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  searchLabel: { color: "white", textAlign: "center", marginStart: 8 },
  contentHeader: {
    paddingHorizontal: 30,
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
  },
  myDevices: { fontSize: 20, color: "white" },
  seeAll: { fontSize: 14, color: "gray" },
  listContainer: {
    marginTop: 8,
    padding: 20,
    flexWrap: "wrap",
    flexDirection: "row",
    paddingBottom: 50,
  },
  card: {
    borderRadius: 30,
    backgroundColor: "#0B0B0B",
    width: width / 2 - 28,
    height: 200,
    margin: 4,
    padding: 16,
    justifyContent: "space-between",
  },
  cardHighlight: { backgroundColor: "#580bdc" },
  cardHeader: { flexDirection: "row", justifyContent: "space-between" },
  descriptionRoom: {
    fontSize: 16,
    color: "white",
    width: width / 4.5,
  },
  iconRoom: {
    height: 40,
    width: 40,
    borderRadius: 100,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  numberDevices: {
    fontSize: 36,
    color: "white",
    fontWeight: "bold",
  },
  devices: {
    fontSize: 14,
    color: "white",
    fontWeight: "300",
  },
});
